# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: server

steps:
- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName'
    serviceConnection: 'Atlas Service Connection'
    method: 'PATCH'
    headers: |
      {
      "Content-Type":"application/json", 
      "Accept": "application/json"
      }
    urlSuffix: '/groups/5d56db41d5ec131e74b498fc/clusters/Cluster0 --digest --include --data ''{"diskSizeGB" : 20}'' --user "XHQUOAXB:35836c59-64bd-4633-b74f-2c0f5e45200e"'
    waitForCompletion: 'false'    
